name: Build Images
"on":
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - cue/**
      - sources/**
      - '*.json'
      - .github/workflows/*.yaml
  pull_request: {}
jobs:
  create-release:
    outputs:
      upload-url: ${{ steps.create-release.outputs.upload_url }}
      id: ${{steps.create-release.outputs.id}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2.3.4
      - id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create release
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{github.ref}} --draft --title "Raspberry Pi USB-C Gadget"
  build-raspios-lite-arm64:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.18"
      - name: Check out repo code
        uses: actions/checkout@v2.3.4
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
      - name: Fetch additional packages
        run: |-
          sudo apt-get update
          sudo apt-get install tree fdisk gdisk qemu-user-static libarchive-tools psmisc tar autoconf make
      - name: Get packer-build-arm plugin
        run: |-
          git clone https://github.com/mkaczanowski/packer-builder-arm plugin
          cd plugin
          go mod download
          go build
      - name: Build the image
        run: |-
          cp plugin/packer-builder-arm .
          sudo packer build raspios-lite-arm64.json | tee build.log || true
          grep "::BUILD::SUCCESS" build.log
          test -f raspios-lite-bookworm-arm64-2024-10-22.img
          zip raspios-lite-bookworm-arm64-2024-10-22.zip raspios-lite-bookworm-arm64-2024-10-22.img
      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber ${{github.ref}} raspios-lite-bookworm-arm64-2024-10-22.zip
  # build-ubuntu-server-arm64:
  #   needs: create-release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v2.1.3
  #       with:
  #         go-version: "1.18"
  #     - name: Check out repo code
  #       uses: actions/checkout@v2.3.4
  #     - name: Use latest Packer
  #       uses: hashicorp-contrib/setup-packer@v1
  #     - name: Fetch additional packages
  #       run: |-
  #         sudo apt-get update
  #         sudo apt-get install tree fdisk gdisk qemu-user-static libarchive-tools psmisc tar autoconf make
  #     - name: Get packer-build-arm plugin
  #       run: |-
  #         git clone https://github.com/mkaczanowski/packer-builder-arm plugin
  #         cd plugin
  #         go mod download
  #         go build
  #     - name: Build the image
  #       run: |-
  #         cp plugin/packer-builder-arm .
  #         sudo packer build ubuntu-server-arm64.json | tee build.log || true
  #         grep "::BUILD::SUCCESS" build.log
  #         test -f ubuntu-server-arm64-22.04.3-arm64.img
  #         zip ubuntu-server-arm64-22.04.3-arm64.img.zip ubuntu-server-arm64-22.04.3-arm64.img
  #     - name: Upload release asset
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: gh release upload --clobber ${{github.ref}} ubuntu-server-arm64-22.04.3-arm64.img.zip
